name: Feature Request
description: Suggest an idea for ClaudeCode4J
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: textarea
    id: api-design
    attributes:
      label: Proposed API Design
      description: If applicable, provide a code sample showing how you envision the API.
      render: java

  - type: dropdown
    id: module
    attributes:
      label: Target Module
      description: Which module should this feature be added to?
      options:
        - claudecode4j-api
        - claudecode4j-core
        - claudecode4j-spring-boot-starter
        - claudecode4j-rest-adapter
        - claudecode4j-kafka-adapter
        - New module
        - Not sure

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I would be willing to submit a PR for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
